#!/usr/bin/env node
// Vercel runs this before `nx build web`. It synthesizes
// apps/web/src/environments/environments.ts from process.env so the real
// file can stay gitignored. Locally, if environments.ts already exists,
// we leave it alone.
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const OUT = resolve('apps/web/src/environments/environments.ts');

const url = process.env['SUPABASE_URL'] ?? '';
const anonKey = process.env['SUPABASE_ANON_KEY'] ?? '';
const adminEmail = process.env['ADMIN_EMAIL'] ?? '';

if (process.env['VERCEL'] && (!url || !anonKey || !adminEmail)) {
  console.error(
    '[gen-env] Missing required env vars on Vercel: SUPABASE_URL, SUPABASE_ANON_KEY, ADMIN_EMAIL.',
  );
  process.exit(1);
}

if (!process.env['VERCEL'] && existsSync(OUT)) {
  console.log('[gen-env] Local environments.ts exists — leaving untouched.');
  process.exit(0);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// Generated by scripts/gen-env.mjs — do not edit.
export const environment = {
  supabase: {
    url: ${JSON.stringify(url)},
    anonKey: ${JSON.stringify(anonKey)},
  },
  admin: { email: ${JSON.stringify(adminEmail)} },
};
`,
);
console.log(`[gen-env] Wrote ${OUT}`);
